version: 0.2

phases:
  install:
    commands:
      - npm install -g redoc-cli
  build:
    commands:
      - npx @redocly/cli build-docs snail.yaml -o redoc.html

artifacts:
  files:
    - redoc.html
